config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get '/topic/:id', to: 'tweets#show', as: 'topic'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout 'application'
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include HTTParty

  def show
    topic = params[:id]

    url = NurelmFront::Application.config.twitter_service + "/tweets/#{topic}.json"
    response = HTTParty.get(url)
    @tweets = response.parsed_response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitter_headline(tweets)
    topic = tweets['tweets'][0]['topic']
    if topic == 'nasa'
      topic = 'NASA'
    else
      topic = topic.capitalize
    end

    minutes_ago = ((Time.now - Time.parse(tweets['tweets'][0]['create_date']))/60).to_i
    result = raw("<h1><div class='twitter-headline'>Recent Tweets for \##{topic}</div></h1>")
    result += raw("<h3 class='twitter-headline'>Results from #{pluralize(minutes_ago, 'minute')} ago.</h3>")
    result += raw("<h3 class='twitter-headline'>New results in #{pluralize((60 - minutes_ago), 'minute')}.</h3>")
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Nurelm Front'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Nurelm Front'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'shared/navigation'
    %main{:role => "main"}
      = render 'shared/messages'
      = yield
  %footer
    .container
      .row
        .col-lg-12
          %ul.list-inline
            %li
              %a{href: root_path} Home
          %p.copyright.text-muted.small Copyright © Josh Hubbard 2016. All Rights Reserved

app/views/pages/index.html.haml
%a{:name => "about"}
.intro-header
  .container
    .row
      .col-lg-12
        .intro-message
          %h1 Twitter Topic Finder
          %h3 Get Information on 3 Awesome Topics!
          %hr.intro-divider
          .col-xs-6.col-md-4.twit-link
            = link_to 'Healthcare', topic_path(:healthcare)
          .col-xs-6.col-md-4.twit-link
            = link_to 'NASA', topic_path(:nasa)
          .col-xs-6.col-md-4.twit-link
            = link_to 'Open Source', topic_path(:opensource)

app/views/shared/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/shared/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse

app/views/tweets/show.html.haml
.intro-header
  .container
    = twitter_headline(@tweets)
    - @tweets['tweets'].each_slice(2) do |tweets|
      .row
        .col-lg-6.center
          %a{href: "http://#{tweets[0]['link']}"}
            %blockquote.twitter-tweet
              %p
                = tweets[0]['text']
              = "- #{tweets[0]['user_name']} (@#{tweets[0]['screen_name']})"
              = link_to DateTime.parse(tweets[0]['create_date']).in_time_zone('Eastern Time (US & Canada)').strftime('%B %e, %Y %l:%M %p'), tweets[0]['link']
        .col-lg-6.center
          %a{href: "http://#{tweets[1]['link']}"}
            %blockquote.twitter-tweet
              %p
                = tweets[1]['text']
              = "- #{tweets[1]['user_name']} (@#{tweets[1]['screen_name']})"
              = link_to DateTime.parse(tweets[1]['create_date']).in_time_zone('Eastern Time (US & Canada)').strftime('%B %e, %Y %l:%M %p'), tweets[1]['link']